//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.XPO.ORMDataModelCode
{

	[Persistent(@"ExternalPrograms")]
	public partial class ExternalProgramsXPO : XPBaseObject
	{
		Guid fId;
		[Key(true)]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		string fName;
		[Size(30)]
		[Nullable(false)]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		string fFileExtension;
		[Size(5)]
		[Nullable(false)]
		public string FileExtension
		{
			get { return fFileExtension; }
			set { SetPropertyValue<string>(nameof(FileExtension), ref fFileExtension, value); }
		}
		string fPathToProgram;
		[Size(400)]
		[Nullable(false)]
		public string PathToProgram
		{
			get { return fPathToProgram; }
			set { SetPropertyValue<string>(nameof(PathToProgram), ref fPathToProgram, value); }
		}
		string fArguments;
		[Size(150)]
		public string Arguments
		{
			get { return fArguments; }
			set { SetPropertyValue<string>(nameof(Arguments), ref fArguments, value); }
		}
		byte[] fImageData;
		[MemberDesignTimeVisibility(true)]
		public byte[] ImageData
		{
			get { return fImageData; }
			set { SetPropertyValue<byte[]>(nameof(ImageData), ref fImageData, value); }
		}
		string fImageExtension;
		[Size(10)]
		public string ImageExtension
		{
			get { return fImageExtension; }
			set { SetPropertyValue<string>(nameof(ImageExtension), ref fImageExtension, value); }
		}
		[Association(@"CommandsXPOReferencesExternalProgramsXPO"), Aggregated]
		public XPCollection<CommandsXPO> Commands { get { return GetCollection<CommandsXPO>(nameof(Commands)); } }
	}

}
