//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"UserAppConfigs")]
	public partial class ORM_UserAppConfigsModel : ORM_BaseModel
	{
		ORM_UsersModel fUser;
		[Persistent(@"IdUser")]
		[DbType("UNIQUEIDENTIFIER")]
		public ORM_UsersModel User
		{
			get { return fUser; }
			set { SetPropertyValue<ORM_UsersModel>(nameof(User), ref fUser, value); }
		}
		long fFrontModules;
		[DbType("BIGINT")]
		public long FrontModules
		{
			get { return fFrontModules; }
			set { SetPropertyValue<long>(nameof(FrontModules), ref fFrontModules, value); }
		}
	}

}
