//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"Commands")]
	[MapInheritance(MapInheritanceType.OwnTable)]
	public partial class ORM_CommandsModel : ORM_BaseModel
	{
		string fName;
		[Indexed(Name = @"UniqueCommandsName", Unique = true)]
		[Size(13)]
		[Nullable(false)]
		[DbType("NVARCHAR(13)")]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		string fDescription;
		[Size(30)]
		[Nullable(false)]
		[DbType("NVARCHAR(30)")]
		public string Description
		{
			get { return fDescription; }
			set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
		}
		string fCommand;
		[Size(4000)]
		[Nullable(false)]
		[DbType("NVARCHAR(4000)")]
		public string Command
		{
			get { return fCommand; }
			set { SetPropertyValue<string>(nameof(Command), ref fCommand, value); }
		}
		bool fIsEnabled;
		[ColumnDefaultValue(true)]
		[DbType("BIT")]
		public bool IsEnabled
		{
			get { return fIsEnabled; }
			set { SetPropertyValue<bool>(nameof(IsEnabled), ref fIsEnabled, value); }
		}
		bool fNeedsAdmin;
		[ColumnDefaultValue(false)]
		[DbType("BIT")]
		public bool NeedsAdmin
		{
			get { return fNeedsAdmin; }
			set { SetPropertyValue<bool>(nameof(NeedsAdmin), ref fNeedsAdmin, value); }
		}
		short fPosition;
		[DbType("TINYINT")]
		public short Position
		{
			get { return fPosition; }
			set { SetPropertyValue<short>(nameof(Position), ref fPosition, value); }
		}
		ORM_UsersModel fUser;
		[Persistent(@"IdUser")]
		[Association(@"ORM_CommandsModelReferencesORM_UsersModel")]
		[DbType("UNIQUEIDENTIFIER")]
		public ORM_UsersModel User
		{
			get { return fUser; }
			set { SetPropertyValue<ORM_UsersModel>(nameof(User), ref fUser, value); }
		}
		ORM_ExternalProgramsModel fExternalProgram;
		[Persistent(@"IdExternalProgram")]
		[Association(@"ORM_CommandsModelReferencesORM_ExternalProgramModel")]
		[DbType("UNIQUEIDENTIFIER")]
		public ORM_ExternalProgramsModel ExternalProgram
		{
			get { return fExternalProgram; }
			set { SetPropertyValue<ORM_ExternalProgramsModel>(nameof(ExternalProgram), ref fExternalProgram, value); }
		}
	}

}
