//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"Images")]
	public partial class ORM_ImagesModel : ORM_BaseModel
	{
		string fName;
		[Indexed(Name = @"UniqueImagesName", Unique = true)]
		[Size(30)]
		[Nullable(false)]
		[DbType("NVARCHAR(30)")]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		byte[] fData;
		[Size(4000)]
		[Nullable(false)]
		[MemberDesignTimeVisibility(true)]
		[DbType("VARBINARY(4000)")]
		public byte[] Data
		{
			get { return fData; }
			set { SetPropertyValue<byte[]>(nameof(Data), ref fData, value); }
		}
		string fFileExtension;
		[Size(10)]
		[Nullable(false)]
		[DbType("NVARCHAR(10)")]
		public string FileExtension
		{
			get { return fFileExtension; }
			set { SetPropertyValue<string>(nameof(FileExtension), ref fFileExtension, value); }
		}
		[PersistentAlias("Contains(Upper([FileExtension]), 'svg')")]
		public bool IsSvg
		{
			get { return (bool)(EvaluateAlias(nameof(IsSvg))); }
		}
		[Association(@"ORM_ExternalProgramModelReferencesORM_ImagesModel"), Aggregated]
		public IList<ORM_ExternalProgramsModel> ORM_ExternalProgramModels { get { return GetList<ORM_ExternalProgramsModel>(nameof(ORM_ExternalProgramModels)); } }
	}

}
