//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"Users")]
	[MapInheritance(MapInheritanceType.OwnTable)]
	public partial class ORM_UsersModel : ORM_BaseModel
	{
		string fUsername;
		[Indexed(Name = @"UniqueUsersUsername", Unique = true)]
		[Size(20)]
		[Nullable(false)]
		[DbType("NVARCHAR(20)")]
		public string Username
		{
			get { return fUsername; }
			set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
		}
		string fEmail;
		[Indexed(Name = @"UniqueUsersEmail", Unique = true)]
		[Size(256)]
		[Nullable(false)]
		[DbType("NVARCHAR(256)")]
		public string Email
		{
			get { return fEmail; }
			set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
		}
		string fSalt;
		[Size(50)]
		[Nullable(false)]
		[DbType("NVARCHAR(50)")]
		public string Salt
		{
			get { return fSalt; }
			set { SetPropertyValue<string>(nameof(Salt), ref fSalt, value); }
		}
		string fPassword;
		[Size(4000)]
		[Nullable(false)]
		[DbType("NVARCHAR(4000)")]
		public string Password
		{
			get { return fPassword; }
			set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
		}
		[Association(@"ORM_NotesModelReferencesORM_UsersModell"), Aggregated]
		public IList<ORM_NotesModel> Notes { get { return GetList<ORM_NotesModel>(nameof(Notes)); } }
		[Association(@"ORM_CommandsModelReferencesORM_UsersModel"), Aggregated]
		public IList<ORM_CommandsModel> Commands { get { return GetList<ORM_CommandsModel>(nameof(Commands)); } }
		[Association(@"ORM_TasksModelReferencesORM_UsersModel"), Aggregated]
		public IList<ORM_TasksModel> Tasks { get { return GetList<ORM_TasksModel>(nameof(Tasks)); } }
	}

}
