//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"ExternalPrograms")]
	[MapInheritance(MapInheritanceType.OwnTable)]
	public partial class ORM_ExternalProgramModel : ORM_BaseModel
	{
		string fName;
		[Indexed(Name = @"UniqueExternalProgramsName", Unique = true)]
		[Size(30)]
		[Nullable(false)]
		[DbType("NVARCHAR(30)")]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		string fFileExtension;
		[Size(5)]
		[Nullable(false)]
		[DbType("NVARCHAR(5)")]
		public string FileExtension
		{
			get { return fFileExtension; }
			set { SetPropertyValue<string>(nameof(FileExtension), ref fFileExtension, value); }
		}
		string fPathToProgram;
		[Size(400)]
		[Nullable(false)]
		[DbType("NVARCHAR(400)")]
		public string PathToProgram
		{
			get { return fPathToProgram; }
			set { SetPropertyValue<string>(nameof(PathToProgram), ref fPathToProgram, value); }
		}
		string fArguments;
		[Size(150)]
		[DbType("NVARCHAR(150)")]
		public string Arguments
		{
			get { return fArguments; }
			set { SetPropertyValue<string>(nameof(Arguments), ref fArguments, value); }
		}
		ORM_ImagesModel fImage;
		[Persistent(@"IdImage")]
		[Association(@"ORM_ExternalProgramModelReferencesORM_ImagesModel")]
		[DbType("UNIQUEIDENTIFIER")]
		public ORM_ImagesModel Image
		{
			get { return fImage; }
			set { SetPropertyValue<ORM_ImagesModel>(nameof(Image), ref fImage, value); }
		}
		[Association(@"ORM_CommandsModelReferencesORM_ExternalProgramModel"), Aggregated]
		public IList<ORM_CommandsModel> Commands { get { return GetList<ORM_CommandsModel>(nameof(Commands)); } }
	}

}
