//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"Notes")]
	[MapInheritance(MapInheritanceType.OwnTable)]
	public partial class ORM_NotesModel : ORM_BaseModel
	{
		string fTitle;
		[Indexed(Name = @"UniqueNotesTitle", Unique = true)]
		[Size(30)]
		[Nullable(false)]
		[DbType("NVARCHAR(30)")]
		public string Title
		{
			get { return fTitle; }
			set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
		}
		string fText;
		[Size(SizeAttribute.Unlimited)]
		public string Text
		{
			get { return fText; }
			set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
		}
		int fColor;
		[DbType("INT")]
		public int Color
		{
			get { return fColor; }
			set { SetPropertyValue<int>(nameof(Color), ref fColor, value); }
		}
		short fPosition;
		[DbType("TINYINT")]
		public short Position
		{
			get { return fPosition; }
			set { SetPropertyValue<short>(nameof(Position), ref fPosition, value); }
		}
		ORM_UsersModel fUser;
		[Persistent(@"IdUser")]
		[Association(@"ORM_NotesModelReferencesORM_UsersModell")]
		[DbType("UNIQUEIDENTIFIER")]
		public ORM_UsersModel User
		{
			get { return fUser; }
			set { SetPropertyValue<ORM_UsersModel>(nameof(User), ref fUser, value); }
		}
	}

}
