//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[OptimisticLocking(OptimisticLockingBehavior.LockModified)]
	[NonPersistent]
	public partial class ORM_BaseModel : XPBaseObject
	{
		Guid fId;
		[Indexed(Name = @"UniqueBaseId", Unique = true)]
		[Key(true)]
		[DbType("UNIQUEIDENTIFIER")]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		DateTime fCreatedAt;
		[DbType("DATETIME2")]
		public DateTime CreatedAt
		{
			get { return fCreatedAt; }
			set { SetPropertyValue<DateTime>(nameof(CreatedAt), ref fCreatedAt, value); }
		}
		DateTime fUpdatedAt;
		[DbType("DATETIME2")]
		public DateTime UpdatedAt
		{
			get { return fUpdatedAt; }
			set { SetPropertyValue<DateTime>(nameof(UpdatedAt), ref fUpdatedAt, value); }
		}
	}

}
