//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Database.ORMDataModel
{

	[Persistent(@"Versions")]
	public partial class ORM_VersionsModel : ORM_BaseModel
	{
		Guid fProgramId;
		[DbType("UNIQUEIDENTIFIER")]
		public Guid ProgramId
		{
			get { return fProgramId; }
			set { SetPropertyValue<Guid>(nameof(ProgramId), ref fProgramId, value); }
		}
		string fName;
		[Size(50)]
		[Nullable(false)]
		[DbType("NVARCHAR(50)")]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		string fVersion;
		[Size(20)]
		[Nullable(false)]
		[DbType("NVARCHAR(20)")]
		public string Version
		{
			get { return fVersion; }
			set { SetPropertyValue<string>(nameof(Version), ref fVersion, value); }
		}
	}

}
