<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en-GB</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PDFsharp" Version="6.2.3" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v25.1">
      <HintPath>..\..\..\..\..\..\..\Program Files\DevExpress 25.1\Components\Offline Packages\devexpress.data\25.1.6\lib\net8.0\DevExpress.Data.v25.1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
