//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Xpo.ModelCode
{

	[Persistent(@"Commands")]
	public partial class CommandXpo : XPBaseObject
	{
		Guid fId;
		[Key(true)]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		UserXpo fUser;
		[Persistent(@"IdUser")]
		[Association(@"CommandsXPOReferencesUsersXPO")]
		public UserXpo User
		{
			get { return fUser; }
			set { SetPropertyValue<UserXpo>(nameof(User), ref fUser, value); }
		}
		ExternalProgramXpo fExternalProgram;
		[Persistent(@"IdExternalProgram")]
		[Association(@"CommandsXPOReferencesExternalProgramsXPO")]
		[DbType("UNIQUEIDENTIFIER")]
		public ExternalProgramXpo ExternalProgram
		{
			get { return fExternalProgram; }
			set { SetPropertyValue<ExternalProgramXpo>(nameof(ExternalProgram), ref fExternalProgram, value); }
		}
		string fName;
		[Size(13)]
		[Nullable(false)]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		string fDescription;
		[Size(30)]
		[Nullable(false)]
		public string Description
		{
			get { return fDescription; }
			set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
		}
		string fText;
		[Size(4000)]
		[Nullable(false)]
		public string Text
		{
			get { return fText; }
			set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
		}
		bool fIsEnabled;
		[ColumnDefaultValue(true)]
		public bool IsEnabled
		{
			get { return fIsEnabled; }
			set { SetPropertyValue<bool>(nameof(IsEnabled), ref fIsEnabled, value); }
		}
		bool fNeedsAdmin;
		[ColumnDefaultValue(false)]
		public bool NeedsAdmin
		{
			get { return fNeedsAdmin; }
			set { SetPropertyValue<bool>(nameof(NeedsAdmin), ref fNeedsAdmin, value); }
		}
		short fPosition;
		public short Position
		{
			get { return fPosition; }
			set { SetPropertyValue<short>(nameof(Position), ref fPosition, value); }
		}
	}

}
