//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Xpo.ModelCode
{

	[Persistent(@"Notes")]
	public partial class NoteXpo : XPBaseObject
	{
		Guid fId;
		[Key(true)]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		UserXpo fUser;
		[Persistent(@"IdUser")]
		[Association(@"NotesXPOReferencesUsersXPO")]
		public UserXpo User
		{
			get { return fUser; }
			set { SetPropertyValue<UserXpo>(nameof(User), ref fUser, value); }
		}
		string fTitle;
		[Size(30)]
		[Nullable(false)]
		public string Title
		{
			get { return fTitle; }
			set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
		}
		string fText;
		[Size(SizeAttribute.Unlimited)]
		public string Text
		{
			get { return fText; }
			set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
		}
		int fColor;
		public int Color
		{
			get { return fColor; }
			set { SetPropertyValue<int>(nameof(Color), ref fColor, value); }
		}
		short fPosition;
		public short Position
		{
			get { return fPosition; }
			set { SetPropertyValue<short>(nameof(Position), ref fPosition, value); }
		}
	}

}
