//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Xpo.ModelCode
{

	[Persistent(@"Todo")]
	public partial class TodoXpo : XPBaseObject
	{
		Guid fId;
		[Key(true)]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		UserXpo fUser;
		[Persistent(@"IdUser")]
		[Association(@"TasksXPOReferencesUsersXPO")]
		public UserXpo User
		{
			get { return fUser; }
			set { SetPropertyValue<UserXpo>(nameof(User), ref fUser, value); }
		}
		string fDescription;
		[Size(350)]
		[Nullable(false)]
		[DbType("NVARCHAR(350)")]
		public string Description
		{
			get { return fDescription; }
			set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
		}
		bool fIsDone;
		[ColumnDefaultValue(false)]
		[DbType("BIT")]
		public bool IsDone
		{
			get { return fIsDone; }
			set { SetPropertyValue<bool>(nameof(IsDone), ref fIsDone, value); }
		}
	}

}
