//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LifeLog.Data.Xpo.Model
{

	[Persistent(@"Users")]
	public partial class UserXpo : XPBaseObject
	{
		Guid fId;
		[Key]
		public Guid Id
		{
			get { return fId; }
			set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
		}
		string fUsername;
		[Size(20)]
		[Nullable(false)]
		public string Username
		{
			get { return fUsername; }
			set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
		}
		string fEmail;
		[Size(256)]
		[Nullable(false)]
		public string Email
		{
			get { return fEmail; }
			set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
		}
		string fSalt;
		[Size(30)]
		[Nullable(false)]
		public string Salt
		{
			get { return fSalt; }
			set { SetPropertyValue<string>(nameof(Salt), ref fSalt, value); }
		}
		string fPassword;
		[Size(128)]
		[Nullable(false)]
		public string Password
		{
			get { return fPassword; }
			set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
		}
		[Association(@"NotesXPOReferencesUsersXPO"), Aggregated]
		public XPCollection<NoteXpo> Notes { get { return GetCollection<NoteXpo>(nameof(Notes)); } }
		[Association(@"TasksXPOReferencesUsersXPO"), Aggregated]
		public XPCollection<TodoXpo> Tasks { get { return GetCollection<TodoXpo>(nameof(Tasks)); } }
		[Association(@"CommandsXPOReferencesUsersXPO"), Aggregated]
		public XPCollection<CommandXpo> Commands { get { return GetCollection<CommandXpo>(nameof(Commands)); } }
	}

}
