//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [OptimisticLocking(false)]
    [DeferredDeletion(false)]
    [NonPersistent]
    public partial class BasePersistentObject : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        [DbType("UNIQUEIDENTIFIER")]
        [System.ComponentModel.DataAnnotations.Key]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        DateTime fCreatedAt;
        [ColumnDbDefaultValue("CURRENT_TIMESTAMP")]
        [DbType("DATETIME2")]
        public DateTime CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<DateTime>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        DateTime fUpdatedAt;
        [ColumnDbDefaultValue("CURRENT_TIMESTAMP")]
        [DbType("DATETIME2")]
        public DateTime UpdatedAt
        {
            get { return fUpdatedAt; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedAt), ref fUpdatedAt, value); }
        }
        bool fEdittingMode;
        [ColumnDefaultValue(false)]
        [NonPersistent]
        public bool EdittingMode
        {
            get { return fEdittingMode; }
            set { SetPropertyValue<bool>(nameof(EdittingMode), ref fEdittingMode, value); }
        }
        bool fSavingMode;
        [ColumnDefaultValue(false)]
        [NonPersistent]
        public bool SavingMode
        {
            get { return fSavingMode; }
            set { SetPropertyValue<bool>(nameof(SavingMode), ref fSavingMode, value); }
        }
    }

}
