//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Notes")]
    [System.ComponentModel.Description("Notes")]
    public partial class ORM_Notes : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [Association(@"ORM_NotesReferencesORM_Users")]
        [DbType("UNIQUEIDENTIFIER")]
        [Core.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        string fTitle;
        [Size(30)]
        [Nullable(false)]
        [DbType("NVARCHAR(30)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(30, MinimumLength = 5)]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fText;
        [Size(4000)]
        [Nullable(false)]
        [DbType("NVARCHAR(4000)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(4000, MinimumLength = 5)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
        }
    }

}
