//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Commands")]
    [System.ComponentModel.Description("Commands")]
    public partial class ORM_Commands : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [Association(@"ORM_CommandsReferencesORM_Users")]
        [DbType("UNIQUEIDENTIFIER")]
        [Core.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        ORM_ExternalPrograms fExternalProgram;
        [Persistent(@"IdExternalProgram")]
        [DbType("UNIQUEIDENTIFIER")]
        [Core.Attributes.Required]
        public ORM_ExternalPrograms ExternalProgram
        {
            get { return fExternalProgram; }
            set { SetPropertyValue<ORM_ExternalPrograms>(nameof(ExternalProgram), ref fExternalProgram, value); }
        }
        string fName;
        [Size(13)]
        [Nullable(false)]
        [DbType("NVARCHAR(13)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(13, MinimumLength = 5)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fType;
        [Size(10)]
        [Nullable(false)]
        [DbType("NVARCHAR(10)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(10, MinimumLength = 2)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        string fDescription;
        [Size(30)]
        [Nullable(false)]
        [DbType("NVARCHAR(30)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(30, MinimumLength = 5)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fCommand;
        [Size(4000)]
        [Nullable(false)]
        [DbType("NVARCHAR(4000)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(4000, MinimumLength = 5)]
        public string Command
        {
            get { return fCommand; }
            set { SetPropertyValue<string>(nameof(Command), ref fCommand, value); }
        }
        bool fEnabled;
        [ColumnDbDefaultValue("0")]
        [DbType("BIT")]
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>(nameof(Enabled), ref fEnabled, value); }
        }
        int fPosition;
        [ColumnDbDefaultValue("0")]
        [DbType("INT")]
        public int Position
        {
            get { return fPosition; }
            set { SetPropertyValue<int>(nameof(Position), ref fPosition, value); }
        }
    }

}
