//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Images")]
    [System.ComponentModel.Description("Images")]
    public partial class ORM_Images : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [Association(@"ImagesReferencesORM_Users")]
        [DbType("UNIQUEIDENTIFIER")]
        [Models.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        string fName;
        [Size(50)]
        [Nullable(false)]
        [DbType("NVARCHAR(50)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        byte[] fData;
        [Nullable(false)]
        [MemberDesignTimeVisibility(true)]
        [Models.Attributes.Required]
        public byte[] Data
        {
            get { return fData; }
            set { SetPropertyValue<byte[]>(nameof(Data), ref fData, value); }
        }
        string fFileExtension;
        [Size(10)]
        [ColumnDbDefaultValue("'.notset'")]
        [Nullable(false)]
        [DbType("NVARCHAR(10)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(10)]
        public string FileExtension
        {
            get { return fFileExtension; }
            set { SetPropertyValue<string>(nameof(FileExtension), ref fFileExtension, value); }
        }
        [PersistentAlias("Contains('[FileExtension]', '.svg')")]
        public bool IsSvg
        {
            get { return (bool)(EvaluateAlias(nameof(IsSvg))); }
        }
    }

}
