//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Users")]
    [System.ComponentModel.Description("Users")]
    public partial class ORM_Users : BasePersistentObject
    {
        string fUsername;
        [Size(20)]
        [Nullable(false)]
        [DbType("NVARCHAR(20)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(20, MinimumLength = 5)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fEmail;
        [Size(256)]
        [Nullable(false)]
        [DbType("NVARCHAR(256)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(256, MinimumLength = 5),
Core.Attributes.EmailValidator]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSalt;
        [Size(50)]
        [Nullable(false)]
        [DbType("NVARCHAR(50)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(50, MinimumLength = 5)]
        public string Salt
        {
            get { return fSalt; }
            set { SetPropertyValue<string>(nameof(Salt), ref fSalt, value); }
        }
        string fPassword;
        [Size(4000)]
        [Nullable(false)]
        [DbType("NVARCHAR(4000)")]
        [Core.Attributes.Required,
Core.Attributes.StringLength(4000, MinimumLength = 5)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        [Association(@"ORM_NotesReferencesORM_Users")]
        public IList<ORM_Notes> User_Notes { get { return GetList<ORM_Notes>(nameof(User_Notes)); } }
        [Association(@"ORM_CommandsReferencesORM_Users")]
        public IList<ORM_Commands> User_Commands { get { return GetList<ORM_Commands>(nameof(User_Commands)); } }
        [Association(@"ImagesReferencesORM_Users")]
        public IList<ORM_Images> User_Images { get { return GetList<ORM_Images>(nameof(User_Images)); } }
        [Association(@"ORM_ExternalProgramsReferencesORM_Users")]
        public IList<ORM_ExternalPrograms> User_ExternalProgramss { get { return GetList<ORM_ExternalPrograms>(nameof(User_ExternalProgramss)); } }
        [Association(@"ORM_PasswordsReferencesORM_Users")]
        public IList<ORM_Passwords> ORM_Passwordss { get { return GetList<ORM_Passwords>(nameof(ORM_Passwordss)); } }
    }

}
