//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Passwords")]
    public partial class ORM_Passwords : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [Association(@"ORM_PasswordsReferencesORM_Users")]
        [DbType("UNIQUEIDENTIFIER")]
        [Models.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        string fName;
        [Size(50)]
        [Nullable(false)]
        [DbType("NVARCHAR(50)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fWebsite;
        [Size(500)]
        [Nullable(false)]
        [DbType("NVARCHAR(500)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(500)]
        public string Website
        {
            get { return fWebsite; }
            set { SetPropertyValue<string>(nameof(Website), ref fWebsite, value); }
        }
        string fLoginUsername;
        [Size(250)]
        [Nullable(false)]
        [DbType("NVARCHAR(250)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(250)]
        public string LoginUsername
        {
            get { return fLoginUsername; }
            set { SetPropertyValue<string>(nameof(LoginUsername), ref fLoginUsername, value); }
        }
        string fLoginPassword;
        [Size(4000)]
        [Nullable(false)]
        [DbType("NVARCHAR(4000)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(4000, MinimumLength = 5)]
        public string LoginPassword
        {
            get { return fLoginPassword; }
            set { SetPropertyValue<string>(nameof(LoginPassword), ref fLoginPassword, value); }
        }
        ORM_Images fImage;
        [Persistent(@"IdImage")]
        [DbType("UNIQUEIDENTIFIER")]
        public ORM_Images Image
        {
            get { return fImage; }
            set { SetPropertyValue<ORM_Images>(nameof(Image), ref fImage, value); }
        }
    }

}
