//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"ModuleSettings")]
    [System.ComponentModel.Description("Module Settings")]
    public partial class ORM_ModuleSettings : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [DbType("UNIQUEIDENTIFIER")]
        [Models.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        bool fEnableNotes;
        [ColumnDefaultValue(false)]
        public bool EnableNotes
        {
            get { return fEnableNotes; }
            set { SetPropertyValue<bool>(nameof(EnableNotes), ref fEnableNotes, value); }
        }
        bool fEnablePasswords;
        [ColumnDefaultValue(false)]
        public bool EnablePasswords
        {
            get { return fEnablePasswords; }
            set { SetPropertyValue<bool>(nameof(EnablePasswords), ref fEnablePasswords, value); }
        }
        bool fEnableTicTacToe;
        [ColumnDefaultValue(false)]
        public bool EnableTicTacToe
        {
            get { return fEnableTicTacToe; }
            set { SetPropertyValue<bool>(nameof(EnableTicTacToe), ref fEnableTicTacToe, value); }
        }
        bool fEnableCoinFilp;
        [ColumnDefaultValue(false)]
        public bool EnableCoinFilp
        {
            get { return fEnableCoinFilp; }
            set { SetPropertyValue<bool>(nameof(EnableCoinFilp), ref fEnableCoinFilp, value); }
        }
        bool fEnableDiceRoll;
        [ColumnDefaultValue(false)]
        public bool EnableDiceRoll
        {
            get { return fEnableDiceRoll; }
            set { SetPropertyValue<bool>(nameof(EnableDiceRoll), ref fEnableDiceRoll, value); }
        }
        bool fEnablePasswordGenerator;
        [ColumnDefaultValue(false)]
        public bool EnablePasswordGenerator
        {
            get { return fEnablePasswordGenerator; }
            set { SetPropertyValue<bool>(nameof(EnablePasswordGenerator), ref fEnablePasswordGenerator, value); }
        }
        bool fEnableMergePdfs;
        [ColumnDefaultValue(false)]
        public bool EnableMergePdfs
        {
            get { return fEnableMergePdfs; }
            set { SetPropertyValue<bool>(nameof(EnableMergePdfs), ref fEnableMergePdfs, value); }
        }
        bool fEnableCommands;
        [ColumnDefaultValue(false)]
        public bool EnableCommands
        {
            get { return fEnableCommands; }
            set { SetPropertyValue<bool>(nameof(EnableCommands), ref fEnableCommands, value); }
        }
    }

}
