//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"Versions")]
    [System.ComponentModel.Description("Versions")]
    public partial class ORM_Versions : BasePersistentObject
    {
        Guid fProgramId;
        [DbType("UNIQUEIDENTIFIER")]
        [Models.Attributes.Required]
        public Guid ProgramId
        {
            get { return fProgramId; }
            set { SetPropertyValue<Guid>(nameof(ProgramId), ref fProgramId, value); }
        }
        string fName;
        [Size(50)]
        [Nullable(false)]
        [DbType("NVARCHAR(50)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(50, MinimumLength = 3)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fVersion;
        [Size(20)]
        [Nullable(false)]
        [DbType("NVARCHAR(20)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(20, MinimumLength = 5)]
        public string Version
        {
            get { return fVersion; }
            set { SetPropertyValue<string>(nameof(Version), ref fVersion, value); }
        }
    }

}
