//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data.ORM.DataModelCode
{

    [Persistent(@"ExternalPrograms")]
    [System.ComponentModel.Description("ExternalPrograms")]
    public partial class ORM_ExternalPrograms : BasePersistentObject
    {
        ORM_Users fUser;
        [Persistent(@"IdUser")]
        [Association(@"ORM_ExternalProgramsReferencesORM_Users")]
        [DbType("UNIQUEIDENTIFIER")]
        [Models.Attributes.Required]
        public ORM_Users User
        {
            get { return fUser; }
            set { SetPropertyValue<ORM_Users>(nameof(User), ref fUser, value); }
        }
        ORM_Images fImage;
        [Persistent(@"IdImage")]
        [DbType("UNIQUEIDENTIFIER")]
        public ORM_Images Image
        {
            get { return fImage; }
            set { SetPropertyValue<ORM_Images>(nameof(Image), ref fImage, value); }
        }
        string fName;
        [Size(50)]
        [Nullable(false)]
        [DbType("NVARCHAR(50)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fFileExtension;
        [Size(5)]
        [Nullable(false)]
        [DbType("NVARCHAR(5)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(5)]
        public string FileExtension
        {
            get { return fFileExtension; }
            set { SetPropertyValue<string>(nameof(FileExtension), ref fFileExtension, value); }
        }
        string fPathToProgram;
        [Size(400)]
        [Nullable(false)]
        [DbType("NVARCHAR(400)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(400)]
        public string PathToProgram
        {
            get { return fPathToProgram; }
            set { SetPropertyValue<string>(nameof(PathToProgram), ref fPathToProgram, value); }
        }
        string fArguments;
        [Size(110)]
        [Nullable(false)]
        [DbType("NVARCHAR(110)")]
        [Models.Attributes.Required,
Models.Attributes.StringLength(110)]
        public string Arguments
        {
            get { return fArguments; }
            set { SetPropertyValue<string>(nameof(Arguments), ref fArguments, value); }
        }
    }

}